<?php

namespace ContainerXTovi1H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCsvUploaderControllerService extends Goreboothero_CsvUploader_KernelTestDebugContainer
{
    /**
     * Gets the public 'Goreboothero\CsvUploader\Http\Controller\CsvUploaderController' shared autowired service.
     *
     * @return \Goreboothero\CsvUploader\Http\Controller\CsvUploaderController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Http/Controller/CsvUploaderController.php';

        return $container->services['Goreboothero\\CsvUploader\\Http\\Controller\\CsvUploaderController'] = new \Goreboothero\CsvUploader\Http\Controller\CsvUploaderController(($container->privates['Goreboothero\\CsvUploader\\Form\\FormFactoryBuilder'] ?? $container->load('getFormFactoryBuilderService')));
    }
}
