<?php

namespace ContainerXTovi1H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileContentTextCharsetValidatorService extends Goreboothero_CsvUploader_KernelTestDebugContainer
{
    /**
     * Gets the private 'Goreboothero\CsvUploader\Validator\FileContentTextCharsetValidator' shared autowired service.
     *
     * @return \Goreboothero\CsvUploader\Validator\FileContentTextCharsetValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/src/Validator/FileContentTextCharsetValidator.php';

        return $container->privates['Goreboothero\\CsvUploader\\Validator\\FileContentTextCharsetValidator'] = new \Goreboothero\CsvUploader\Validator\FileContentTextCharsetValidator();
    }
}
