<?php

namespace ContainerXTovi1H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormFactoryBuilderService extends Goreboothero_CsvUploader_KernelTestDebugContainer
{
    /**
     * Gets the private 'Goreboothero\CsvUploader\Form\FormFactoryBuilder' shared autowired service.
     *
     * @return \Goreboothero\CsvUploader\Form\FormFactoryBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Form/FormFactoryBuilder.php';
        include_once \dirname(__DIR__, 4).'/src/Validator/ValidatorBuilder.php';

        return $container->privates['Goreboothero\\CsvUploader\\Form\\FormFactoryBuilder'] = new \Goreboothero\CsvUploader\Form\FormFactoryBuilder(($container->privates['Goreboothero\\CsvUploader\\Validator\\ValidatorBuilder'] ?? ($container->privates['Goreboothero\\CsvUploader\\Validator\\ValidatorBuilder'] = new \Goreboothero\CsvUploader\Validator\ValidatorBuilder())));
    }
}
