<?php

namespace ContainerXTovi1H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getValidatorBuilderService extends Goreboothero_CsvUploader_KernelTestDebugContainer
{
    /**
     * Gets the private 'Goreboothero\CsvUploader\Validator\ValidatorBuilder' shared autowired service.
     *
     * @return \Goreboothero\CsvUploader\Validator\ValidatorBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Validator/ValidatorBuilder.php';

        return $container->privates['Goreboothero\\CsvUploader\\Validator\\ValidatorBuilder'] = new \Goreboothero\CsvUploader\Validator\ValidatorBuilder();
    }
}
