<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHICAK8B\Goreboothero_CsvUploader_Http_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHICAK8B/Goreboothero_CsvUploader_Http_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerHICAK8B.legacy');

    return;
}

if (!\class_exists(Goreboothero_CsvUploader_Http_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerHICAK8B\Goreboothero_CsvUploader_Http_KernelTestDebugContainer::class, Goreboothero_CsvUploader_Http_KernelTestDebugContainer::class, false);
}

return new \ContainerHICAK8B\Goreboothero_CsvUploader_Http_KernelTestDebugContainer([
    'container.build_hash' => 'HICAK8B',
    'container.build_id' => '689adba2',
    'container.build_time' => 1608382259,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHICAK8B');
