<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXTovi1H\Goreboothero_CsvUploader_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXTovi1H/Goreboothero_CsvUploader_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerXTovi1H.legacy');

    return;
}

if (!\class_exists(Goreboothero_CsvUploader_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerXTovi1H\Goreboothero_CsvUploader_KernelTestDebugContainer::class, Goreboothero_CsvUploader_KernelTestDebugContainer::class, false);
}

return new \ContainerXTovi1H\Goreboothero_CsvUploader_KernelTestDebugContainer([
    'container.build_hash' => 'XTovi1H',
    'container.build_id' => '7167aa2d',
    'container.build_time' => 1612070395,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXTovi1H');
